baseURL = "https://aiforkids.in/"
title = "Aiforkids "

languageCode = "en-us"
DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Lalit Kumar"
  github = "https://github.com/lalitkumarofficial"
  facebook = "https://facebook.com/aiforkidsofficial"
  og_image = "/images/aiforkids-logo.png"
  sitename = "Aiforkids"
  twitter = "@aiforkidsofficial"
  logoUrl = "/images/aiforkids-logo.png"

[languages]
  [languages.en]
    languageName = "en"
    languageCode = "en-us"
    weight = 1
[outputs]
  home = ["HTML", "RSS", "JSON"]
  
[taxonomies]
  category = "categories"
  tag = "tags"